export const category = [
  "Agriculture",
  "Artisan",
  "Construction",
  "Education",
  "Entertainment",
  "Event Management",
  "Food/restaurant",
  "Information Management",
  "medical",
  "Manufacturing",
  "minning",
  "professional service",
  "real estate",
  "utility",
  "Waste Management",
];

export const serviceList = [
  "Project Manager",
  "Site Supervisor",
  "Architect",
  "Civil Engineer",
  "Structural Engineer",
  "Electrician",
  "Bricklayer",
  "Plumber",
  "Carpenter",
  "Mason",
  "Painter",
  "Welder",
  "Steel Fixer",
  "Crane Operator",
  "Laborer",
  "Surveyor",
  "Safety Officer",
  "Others",
];
