export const ROUTES = {
  HOME: "/",
  ABOUT_US: "/about-us",
  POLICY: "/policy",
  TERMS_OF_USE: "/terms",
  COOKIE_POLICY: "/cookie-policy",
  HOW_IT_WORKS: "/how",
  FAQ: "/faq",
  GUIDES: "/guides",
  HELP_CENTER: "/help-center",
  BLOGS: "/blogs",
  NEWS: "/news",
  TIPS: "/tips",
  TESTIMONIALS: "/testimonial",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  VERIFY_EMAIL: (email: string) => `/verify-email/${encodeURIComponent(email)}`,
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: (email: string) =>
    `/reset-password/${encodeURIComponent(email)}`,
  SEARCH_SERVICE: "/catalog/services?",
  FIND_JOB: "/find-job",
  HIRE_EXPERT: "/hire-experts",
  BUY_MATERIALS: "/buy-materials",
  PRIVATE_EXPERT: "/expert/private-expert",
  JOIN_EXPERT: "/expert/register",
  LIST_NEW_JOB: "/dashboard/job/list-new-job",
  PLANNED_MAINTENANCE: "/dashboard/planned-maintenance",
  DASHBOARD_JOB: "/dashboard/job",
  GENERAL_BIDDABLE_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/biddable/${id}`,
  GENERAL_REGULAR_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/regular/${id}`,
  GENERAL_DIRECT_JOB_DETAILS: (id: string) =>
    `/dashboard/job/info/direct/${id}`,
  GENERAL_EXPERT_DETAILS: (id: string) => `/expert/info/${id}`,
  DASHBOARD_MATERIAL: `/dashboard/material`,
  GENERAL_MATERIAL_DETAILS: (id: string) => `/material/info/${id}`,
  CART: "/dashboard/cart",
} as const;
